/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as KnowledgeCenterRouteImport } from './routes/knowledge-center'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as EventsRouteImport } from './routes/events'
import { Route as CropAdvisoryRouteImport } from './routes/crop-advisory'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ServiceAreasAreaRouteImport } from './routes/service-areas.$area'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as KnowledgeCenterSlugRouteImport } from './routes/knowledge-center.$slug'
import { Route as AdminLoginRouteImport } from './routes/admin.login'

const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeCenterRoute = KnowledgeCenterRouteImport.update({
  id: '/knowledge-center',
  path: '/knowledge-center',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const CropAdvisoryRoute = CropAdvisoryRouteImport.update({
  id: '/crop-advisory',
  path: '/crop-advisory',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAreasAreaRoute = ServiceAreasAreaRouteImport.update({
  id: '/service-areas/$area',
  path: '/service-areas/$area',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProductsRoute,
} as any)
const KnowledgeCenterSlugRoute = KnowledgeCenterSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => KnowledgeCenterRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/crop-advisory': typeof CropAdvisoryRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/knowledge-center': typeof KnowledgeCenterRouteWithChildren
  '/products': typeof ProductsRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/knowledge-center/$slug': typeof KnowledgeCenterSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/service-areas/$area': typeof ServiceAreasAreaRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/crop-advisory': typeof CropAdvisoryRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/knowledge-center': typeof KnowledgeCenterRouteWithChildren
  '/products': typeof ProductsRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/knowledge-center/$slug': typeof KnowledgeCenterSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/service-areas/$area': typeof ServiceAreasAreaRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/crop-advisory': typeof CropAdvisoryRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/knowledge-center': typeof KnowledgeCenterRouteWithChildren
  '/products': typeof ProductsRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/knowledge-center/$slug': typeof KnowledgeCenterSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/service-areas/$area': typeof ServiceAreasAreaRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/community'
    | '/contact'
    | '/crop-advisory'
    | '/events'
    | '/gallery'
    | '/knowledge-center'
    | '/products'
    | '/admin/login'
    | '/knowledge-center/$slug'
    | '/products/$slug'
    | '/service-areas/$area'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/community'
    | '/contact'
    | '/crop-advisory'
    | '/events'
    | '/gallery'
    | '/knowledge-center'
    | '/products'
    | '/admin/login'
    | '/knowledge-center/$slug'
    | '/products/$slug'
    | '/service-areas/$area'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/community'
    | '/contact'
    | '/crop-advisory'
    | '/events'
    | '/gallery'
    | '/knowledge-center'
    | '/products'
    | '/admin/login'
    | '/knowledge-center/$slug'
    | '/products/$slug'
    | '/service-areas/$area'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CommunityRoute: typeof CommunityRoute
  ContactRoute: typeof ContactRoute
  CropAdvisoryRoute: typeof CropAdvisoryRoute
  EventsRoute: typeof EventsRoute
  GalleryRoute: typeof GalleryRoute
  KnowledgeCenterRoute: typeof KnowledgeCenterRouteWithChildren
  ProductsRoute: typeof ProductsRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  ServiceAreasAreaRoute: typeof ServiceAreasAreaRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-center': {
      id: '/knowledge-center'
      path: '/knowledge-center'
      fullPath: '/knowledge-center'
      preLoaderRoute: typeof KnowledgeCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crop-advisory': {
      id: '/crop-advisory'
      path: '/crop-advisory'
      fullPath: '/crop-advisory'
      preLoaderRoute: typeof CropAdvisoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas/$area': {
      id: '/service-areas/$area'
      path: '/service-areas/$area'
      fullPath: '/service-areas/$area'
      preLoaderRoute: typeof ServiceAreasAreaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/knowledge-center/$slug': {
      id: '/knowledge-center/$slug'
      path: '/$slug'
      fullPath: '/knowledge-center/$slug'
      preLoaderRoute: typeof KnowledgeCenterSlugRouteImport
      parentRoute: typeof KnowledgeCenterRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface KnowledgeCenterRouteChildren {
  KnowledgeCenterSlugRoute: typeof KnowledgeCenterSlugRoute
}

const KnowledgeCenterRouteChildren: KnowledgeCenterRouteChildren = {
  KnowledgeCenterSlugRoute: KnowledgeCenterSlugRoute,
}

const KnowledgeCenterRouteWithChildren = KnowledgeCenterRoute._addFileChildren(
  KnowledgeCenterRouteChildren,
)

interface ProductsRouteChildren {
  ProductsSlugRoute: typeof ProductsSlugRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsSlugRoute: ProductsSlugRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CommunityRoute: CommunityRoute,
  ContactRoute: ContactRoute,
  CropAdvisoryRoute: CropAdvisoryRoute,
  EventsRoute: EventsRoute,
  GalleryRoute: GalleryRoute,
  KnowledgeCenterRoute: KnowledgeCenterRouteWithChildren,
  ProductsRoute: ProductsRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  ServiceAreasAreaRoute: ServiceAreasAreaRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
